backend:
  name: github
  repo: kartik2406/product-info
  branch: master
publish_mode: editorial_workflow
media_folder: static/images
collections:
  - name: product
    label: Product
    folder: src/products
    extension: md
    format: frontmatter
    create: true
    identifier_field: name
    fields:
      - { name: name, label: "Name of the product" }
      - { name: price, label: Price, widget: "number" }
      - { name: description, label: Description }
